var num1 = 32;
var num2 = 12;
var subtract = num1 - num2;
console.log(subtract);
var multiply = num1 * num2;
console.log(multiply);
var divided = num1 / num2;
console.log(divided);
var modulus = num1 % num2;
console.log(modulus);